const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'static/index.html'),'utf8');
const dom=new JSDOM(html,{url:'http://localhost:8423',runScripts:'outside-only'}),w=dom.window,$=id=>w.document.getElementById(id);
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
w.eval(fs.readFileSync(path.join(root,'static/workspace.js'),'utf8'));
w.eval(fs.readFileSync(path.join(root,'static/app.js'),'utf8').replace('init().catch(e=>toast(e.message));','')+'\nwindow.ist=importsState;window.s=state;');
const details=['routeStatistics','selectedWeightDetails','routeLibraryDetails','routeOptions','bulkCoverage','bulkStatistics'];
for(const id of details){assert.equal($(id).tagName,'DETAILS');assert.equal($(id).open,false,id);}
assert.equal($('routeWorkspace').hidden,false);assert.equal($('bulkPanel').hidden,true);
assert.deepEqual([...w.document.querySelectorAll('[data-workspace]')].map(x=>x.dataset.workspace),['route','bulk','documents']);
for(const id of ['rateChart','matrixBody'])assert.equal($(id).closest('details'),null,'main comparison stays visible');
assert.ok($('bulkCoverageRows').closest('details'));assert.ok($('exactCount').closest('#routeStatistics'));
const ids=[...w.document.querySelectorAll('[id]')].map(n=>n.id);assert.equal(new Set(ids).size,ids.length,'no duplicate control IDs');
assert.ok($('importApplyFeedback').parentElement.contains($('importApplyButton')),'receipt at the clicked button');
assert.ok(!$('appliedFileFeedback').closest('details'),'main file confirmation always visible');
$('originSelect').innerHTML='<option>Москва</option>';$('destinationSelect').innerHTML='<option>Санкт-Петербург</option>';$('importCompany').innerHTML='<option>ДЛ</option>';
w.s.options={profiles:[],companies:[{id:'ДЛ',label:'ДЛ'}]};w.ist.route={origin:'Москва',destination:'Санкт-Петербург'};
w.ist.token='one-use-token';$('importConfirmed').checked=true;$('importDialog').showModal();w.importBusy(false);
let calls=0,finish;w.getJSON=async(url,options)=>{assert.equal(url,'/api/import/commit');calls++;return new Promise(resolve=>finish=resolve);};
w.loadOptions=async()=>{throw Error('Refresh unavailable after successful save')};
(async()=>{
 const job=w.applyImport();assert.equal(calls,1);assert.match($('importApplyButton').textContent,/Применяю/);assert.equal($('importApplyButton').disabled,true);assert.equal($('importApplyButton').getAttribute('aria-busy'),'true');
 await w.applyImport();assert.equal(calls,1,'no duplicate request while applying');w.closeImport();assert.equal($('importDialog').open,true);
 finish({company:'ДЛ',origin:'Москва',destination:'Санкт-Петербург',rows:28,meta:{original_filename:'price <b>test</b>.pdf'}});await job;
 assert.match($('importApplyFeedback').textContent,/Цены применены/);assert.match($('importApplyFeedback').textContent,/28 цен/);assert.equal($('importApplyFeedback').querySelector('b'),null,'filename is plain text');
 assert.match($('importApplyFeedback').textContent,/Не удалось обновить экран/);assert.doesNotMatch($('importApplyFeedback').textContent,/Не удалось подтвердить применение/);
 assert.equal($('importApplyFeedback').classList.contains('error'),false);assert.equal($('importApplyButton').disabled,true);assert.equal($('importApplyButton').textContent,'✓ Цены применены');assert.equal($('importDoneButton').hidden,false);assert.equal($('importDoneButton'),w.document.activeElement);
 assert.match($('appliedFileFeedback').textContent,/применён/);await w.applyImport();assert.equal(calls,1,'successful commit cannot be repeated');
 $('importDoneButton').click();assert.equal($('importDialog').open,false);
 w.ist.token='retry-token';$('importConfirmed').checked=true;$('importDialog').showModal();w.getJSON=async()=>{throw Error('HTTP 503')};await w.applyImport();
 assert.equal($('importApplyFeedback').hidden,false);assert.equal($('importApplyFeedback').classList.contains('error'),true);assert.match($('importApplyFeedback').textContent,/HTTP 503/);assert.equal($('importApplyButton').disabled,false);assert.equal(w.ist.token,'retry-token');assert.equal($('importDoneButton').hidden,true);
 w.resetImportPreview();assert.equal($('importApplyFeedback').hidden,true);assert.equal($('importApplyButton').textContent,'Применить цены из файла');
 w.renderJob({origin:'Москва',destination:'Санкт-Петербург',status:'running',requested_companies:['ДЛ'],completed_companies:0,results:[]});assert.equal($('routeLoadStatus').hidden,false);assert.match($('routeLoadStatus').textContent,/0 из 1/);assert.equal($('routeStatistics').open,false);
 dom.window.close();console.log('PASS: route first, advanced reports folded, chart/matrix visible, receipt beside action, applying/success/error, retry and no duplicate commit, progress outside folded statistics');
})().catch(e=>{console.error(e);process.exit(1)});
