"""Durable, explicitly confirmed user tariffs, separate from network results."""
from __future__ import annotations

import hashlib
import math
import re
import uuid
from datetime import date, datetime
from pathlib import Path

from . import v42_engine as e
from .tariff_documents import parse_document, normalize_filename, MAX_BYTES

PREVIEW_TTL = 1800


def root():
    return e.RUNTIME_DIR / 'imports'


def revision():return int(e._read_json(root()/'revision.json',{}).get('revision',0))


def bump_revision():e._robust_json_write(root()/'revision.json',{'revision':revision()+1})


def route_path(origin, destination):
    return root() / 'routes' / (e._route_cfg(origin,destination)['slug']+'.json')


def pack(origin, destination):
    from .price_library import pack as multi_pack
    result=multi_pack(origin,destination)
    legacy=_legacy_pack(origin,destination)
    for rows in legacy.get('profiles',{}).values():
        for company,row in rows.items():legacy.setdefault('companies',{}).setdefault(company,row)
    def order(meta):return (int(meta.get('import_revision',0)),str(meta.get('uploaded_at','')))
    for company,meta in legacy.get('companies',{}).items():
        if order(meta)>=order(result['companies'].get(company,{})):
            result['companies'][company]=meta
            for rows in result['profiles'].values():rows.pop(company,None)
            for pid,rows in legacy.get('profiles',{}).items():
                if company in rows:result['profiles'].setdefault(pid,{})[company]=rows[company]
    result['companies']={c:m for c,m in result['companies'].items() if not m.get('_disabled')}
    return result


def _legacy_pack(origin,destination):
    return e._read_json(route_path(origin,destination),{'companies':{},'profiles':{}})


def _validate(company, origin, destination):
    origin,destination=e.route_pair(origin,destination)
    if company not in e.COMPANIES or not e.is_supported_route(origin,destination):
        raise ValueError('Выберите компанию и два разных города из списка')
    return origin,destination


def _check_values(values):
    if not values:raise ValueError('В документе нет распознанных тарифов выбранного маршрута')
    for pid,row in values.items():
        price=row.get('price')
        if pid not in e.PROFILE_BY_ID or row.get('kind')!='exact' or isinstance(price,bool) or not isinstance(price,(int,float)) or not math.isfinite(price) or price<=0:
            raise ValueError('Документ содержит некорректную цену или вес')
        for key in ('rate_per_kg','minimum'):
            value=row.get(key)
            if value is not None and (isinstance(value,bool) or not isinstance(value,(int,float)) or not math.isfinite(value) or value<=0):raise ValueError('Некорректная ставка или минимум')


def _token_path(token):
    if not re.fullmatch(r'[a-f0-9]{32}',str(token)):
        raise ValueError('Предпросмотр не найден; загрузите документ заново')
    return root()/'pending'/(token+'.json')


def cleanup_pending():
    pending=root()/'pending'
    if not pending.exists():return
    for p in pending.glob('*.json'):
        try:
            if datetime.now().timestamp()-p.stat().st_mtime>PREVIEW_TTL:
                data=e._read_json(p,{})
                token=p.stem
                # Pending file names are generated by us; never follow a stored arbitrary path.
                for file in pending.glob(token+'.*'):file.unlink(missing_ok=True)
        except OSError:pass


def preview(raw, filename, company, origin, destination):
    origin,destination=_validate(company,origin,destination)
    if len(raw)>MAX_BYTES:raise ValueError('Максимальный размер документа — 20 МБ')
    values,parsed=parse_document(raw,filename,company,origin,destination)
    _check_values(values)
    warnings=['Это документ пользователя. Его загрузка не подтверждает, что перевозчик применяет эти цены сейчас.']
    stamp=parsed.get('document_date')
    if stamp:
        d=date.fromisoformat(stamp)
        if d>date.today():raise ValueError('В документе указана будущая дата тарифов; текущие цены не заменены')
        if (date.today()-d).days>30:warnings.append('Дата в документе старше 30 дней. Проверьте актуальность у перевозчика.')
    else:warnings.append('Дата действия тарифов в документе не распознана. Проверьте её в оригинале.')
    if len(values)<len(e.COMMON_PROFILES):warnings.append('Часть весов отсутствует в файле. Для них сохранится отдельный онлайн/архивный источник; значения не будут достроены.')
    token=uuid.uuid4().hex
    name=normalize_filename(filename)
    if name!=str(filename):warnings.append('Имя файла исправлено: '+name+'. Содержимое проверено отдельно.')
    ext=Path(name).suffix.lower()
    meta={**parsed,'original_filename':name,'sha256':hashlib.sha256(raw).hexdigest(),
          'company':company,'origin':origin,'destination':destination,'created_at':e._now(),
          'source_type':'Файл пользователя · '+str(parsed.get('parser') or ext.upper()),
          'data_origin':'uploaded','source_url':None,'warnings':warnings,'token':token,'extension':ext}
    with e.STATE_LOCK:
        cleanup_pending()
        pending=_token_path(token);pending.parent.mkdir(parents=True,exist_ok=True)
        pending.with_suffix(ext).write_bytes(raw)
        e._robust_json_write(pending,{'meta':meta,'values':values})
    return {'token':token,'company':company,'origin':origin,'destination':destination,'meta':meta,
            'warnings':warnings,'rows':[{'profile':p,**values[p['id']]} for p in e.COMMON_PROFILES if p['id'] in values],
            'missing_profiles':[p['label'] for p in e.COMMON_PROFILES if p['id'] not in values]}


def commit(token):
    with e.STATE_LOCK:
        pending=_token_path(token);data=e._read_json(pending,{})
        if not data or e.age_seconds(data['meta'].get('created_at'))>PREVIEW_TTL:
            raise ValueError('Предпросмотр истёк. Загрузите файл заново и проверьте цены')
        meta=data['meta'];values=data['values'];_check_values(values)
        company=meta['company'];o,d=_validate(company,meta['origin'],meta['destination'])
        source=pending.with_suffix(meta['extension']);raw=source.read_bytes()
        if hashlib.sha256(raw).hexdigest()!=meta['sha256']:
            raise ValueError('Файл изменился после предпросмотра; сохранение отменено')
        filename=token+meta['extension'];target=root()/'files'/filename
        target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(raw)
        saved={**meta,'import_revision':revision()+1,'source_file':filename,'uploaded_at':e._now(),'captured_at':e._now(),'online':False}
        current=_legacy_pack(o,d)
        # Replace only this carrier in this ordered route. Old imported weights
        # are removed even when the replacement document has fewer rows.
        for rows in current.setdefault('profiles',{}).values():rows.pop(company,None)
        current.setdefault('companies',{})[company]=saved
        for pid,row in values.items():current['profiles'].setdefault(pid,{})[company]={**saved,**row}
        e._robust_json_write(route_path(o,d),current)
        bump_revision()
        pending.unlink(missing_ok=True);source.unlink(missing_ok=True)
        return {'ok':True,'company':company,'origin':o,'destination':d,'rows':len(values),'meta':saved}


def remove(company, origin, destination):
    o,d=_validate(company,origin,destination)
    with e.STATE_LOCK:
        from .price_library import disable_route
        disable_route(company,o,d)
        current=_legacy_pack(o,d);current.setdefault('companies',{}).pop(company,None)
        for rows in current.setdefault('profiles',{}).values():rows.pop(company,None)
        e._robust_json_write(route_path(o,d),current)
        bump_revision()
    return {'ok':True}


def source_file(filename):
    if not re.fullmatch(r'[a-f0-9]{32}\.(pdf|xlsx|xls|zip|csv)',filename):
        raise FileNotFoundError('Файл не найден')
    p=root()/'files'/filename
    if not p.is_file():raise FileNotFoundError('Файл не найден')
    return p
